import React, { useState } from 'react';
import {FixFirstPanel} from '../components/FixFirstPanel';
import { Activity, ArrowDownToLine, ArrowRight, Check, CheckCheck, CircleHelp, FileSearch, Fingerprint, LockKeyhole, Network, Search, ShieldAlert, ShieldCheck } from 'lucide-react';
import { Investigation, NetworkConnection, SecurityFinding, ActiveTab } from '../types';
import { CumulativeAnalytics } from '../services/analytics';
interface Props {investigation:Investigation;selectedConnection:NetworkConnection|null;onSelectConnection:(c:NetworkConnection)=>void;onSelectFinding:(f:SecurityFinding)=>void;onNavigateToSimulator?:(p:string)=>void;onNavigateToReplay?:(r:string)=>void;cumulativeAnalytics:CumulativeAnalytics;onNavigate?:(tab:ActiveTab)=>void}
export const OverviewPage:React.FC<Props> = ({investigation:inv,onSelectConnection,onSelectFinding,onNavigate}) => {
  const [query,setQuery]=useState(''); const [protocol,setProtocol]=useState('ALL');
  const total=inv.connections.length;
  const negotiated=inv.connections.filter(c=>c.tls_version!=='None'&&c.tls_version!=='UNKNOWN').length;
  const issues=inv.findings.filter(f=>f.status==='FAIL'||f.status==='WARN').sort((a,b)=>['CRITICAL','HIGH','MEDIUM','LOW','INFO'].indexOf(a.severity)-['CRITICAL','HIGH','MEDIUM','LOW','INFO'].indexOf(b.severity));
  const gap=inv.findings.filter(f=>f.status==='UNKNOWN').length;
  const percent=total?Math.round(negotiated/total*100):0;
  const sessions=inv.connections.filter(c=>(protocol==='ALL'||c.protocol===protocol)&&`${c.source_label} ${c.target_label} ${c.protocol} ${c.tls_version} ${c.cipher_suite}`.toLowerCase().includes(query.toLowerCase()));
  return <div className="dashboard-enter space-y-6">
    <div className="page-heading"><div><div className="eyebrow">CAPTURE INTELLIGENCE</div><h1>Email security, in focus.</h1><p>Follow the evidence. Understand the risk. Secure every connection.</p></div><div className="flex gap-3"><button className="button-secondary" onClick={()=>onNavigate?.('report')}><ArrowDownToLine size={16}/> Export report</button><button className="button-primary" onClick={()=>onNavigate?.('upload')}><FileSearch size={17}/> Analyze capture</button></div></div>
    <div className="capture-strip"><div className="flex items-center gap-3 min-w-0"><span className="file-icon"><FileSearch size={19}/></span><div className="min-w-0"><strong className="block truncate">{inv.filename}</strong><span>{inv.is_simulated?'Illustrative dataset · not packet-derived evidence':inv.capture_origin==='SYNTHETIC_LAB'?'Synthetic lab traffic · analyzed from actual PCAP bytes':'Uploaded packet capture · origin not independently verified'}</span></div></div><div className="capture-hash" title={inv.sha256_hash||'No source capture'}><Fingerprint size={15}/>{!inv.is_simulated&&!inv.is_simulated&&inv.sha256_short?`SHA-256 ${inv.sha256_short}`:'DEMO DATA'}<span className="text-slate-600 mx-2">|</span><Check size={14}/><span>Analysis complete</span></div></div>
    <div className="metric-grid">{[
      {label:'Mail sessions',value:total,caption:'SMTP · IMAP · POP3',icon:Network,tone:'sky'},
      {label:'TLS selections observed',value:negotiated,caption:`${percent}% of captured mail sessions`,icon:LockKeyhole,tone:'mint'},
      {label:'Actionable findings',value:issues.length,caption:`${issues.filter(f=>f.severity==='CRITICAL').length} critical priority`,icon:ShieldAlert,tone:'rose'},
      {label:'Evidence gaps',value:gap,caption:'Checks requiring more evidence',icon:CircleHelp,tone:'amber'},
    ].map(({label,value,caption,icon:Icon,tone})=><section className="metric-card" key={label}><div className="flex items-center justify-between"><span>{label}</span><Icon size={18} className={`tone-${tone}`}/></div><strong>{value.toString().padStart(2,'0')}</strong><small>{caption}</small></section>)}</div>
    <div className="insights-grid">
      <section className="panel posture-panel"><div className="panel-title"><h2>Transport posture</h2><span className="mini-label">CURRENT CAPTURE</span></div><div className="posture-content"><div className="posture-ring" style={{background:`conic-gradient(#62dfbc ${percent}%, #24313c 0)`}}><div><strong>{percent}<small>%</small></strong><span>TLS observed</span></div></div><div className="posture-copy"><span className={`risk-badge ${issues.length?'risk-high':'risk-neutral'}`}>{(inv.security_posture?.status||'UNKNOWN').replace(/_/g,' ')}</span><h3>{issues.length?'Remediation needed':gap?'More evidence needed':total?'Baseline checks passed':'No mail sessions found'}</h3><p>{issues.length?'Prioritize the findings below, then validate the hardened configuration with a fresh capture.':'Review capture coverage and certificate trust before drawing a security conclusion.'}</p><span className="subtle-note">TLS visibility is a coverage measure, not a security score.</span></div></div><div className="posture-footer"><span><CheckCheck size={14}/>{inv.security_posture?.passed_checks||0} checks passed</span><span><CircleHelp size={14}/>{gap} unverified</span></div></section>
      <section className="panel protocol-panel"><div className="panel-title"><h2>Protocol distribution</h2><Activity size={17} className="text-slate-500"/></div><p className="panel-subtitle">Observed email transport sessions</p>{['SMTP','IMAP','POP3'].map((p,i)=>{const count=inv.connections.filter(c=>c.protocol===p).length;return <div className="protocol-row" key={p}><div><span><i style={{background:['#63dfbd','#78b9ed','#b1a1e8'][i]}}/>{p}</span><strong>{count} <small>sessions</small></strong></div><div className="protocol-track"><span style={{width:`${total?count/total*100:0}%`,background:['#63dfbd','#78b9ed','#b1a1e8'][i]}}/></div></div>})}<div className="text-xs text-slate-500 mt-5">Port-based identification is inferred when application commands are encrypted.</div></section>
    </div>
    <FixFirstPanel value={inv.fix_first} onSelect={id=>{const f=inv.findings.find(f=>f.id===id);if(f)onSelectFinding(f)}}/>
    <section className="panel"><div className="panel-title"><div className="flex items-center gap-2"><ShieldAlert size={18} className="text-rose-300"/><h2>Prioritized findings</h2><span className="count-pill">{issues.length}</span></div><button className="text-link" onClick={()=>onNavigate?.('findings')}>View all findings <ArrowRight size={14}/></button></div>{issues.length?<div className="priority-list">{issues.slice(0,3).map((f,i)=><button className="priority-row" key={f.id} onClick={()=>onSelectFinding(f)}><span className="priority-number">0{i+1}</span><span className="priority-description"><strong>{f.title}</strong><small>{f.location} <span className="mx-2">·</span> {f.rule_id}</small></span><span className={`severity-chip ${f.severity.toLowerCase()}`}>{f.severity}</span><ArrowRight size={17} className="text-slate-500"/></button>)}</div>:<div className="empty-state"><ShieldCheck size={22}/>No actionable findings in the observed evidence. Review unverified checks separately.</div>}</section>
    <section className="panel"><div className="panel-title"><div className="flex items-center gap-2"><Network size={18} className="text-sky-300"/><h2>Captured sessions</h2><span className="count-pill">{total}</span></div><span className="mini-label">SELECT A SESSION TO INVESTIGATE</span></div><div className="session-tools"><label className="search-field"><Search size={16}/><input aria-label="Search sessions" placeholder="Search endpoint, version or cipher…" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="filter-tabs">{['ALL','SMTP','IMAP','POP3'].map(p=><button aria-pressed={protocol===p} key={p} className={protocol===p?'active':''} onClick={()=>setProtocol(p)}>{p==='ALL'?'All protocols':p}</button>)}</div></div><div className="table-scroll"><table className="session-table"><thead><tr><th>Connection</th><th>Protocol</th><th>Negotiated TLS</th><th>Transport</th><th>Assessment</th><th/></tr></thead><tbody>{sessions.map(c=><tr key={c.id} onClick={()=>onSelectConnection(c)}><td><button className="endpoint-button" onClick={e=>{e.stopPropagation();onSelectConnection(c)}}>{c.source_label.match(/\(([^)]+)\)/)?.[1]||c.source_label} <ArrowRight size={12}/> {c.target_label.match(/\(([^)]+)\)/)?.[1]||c.target_label}</button><small>{c.session_id} · {c.evidence.packet_count} packets</small></td><td><span className="protocol-tag">{c.protocol}</span></td><td className="font-mono">{c.tls_version==='None'?'Not observed':c.tls_version}</td><td>{c.transport_mode.includes('Implicit')?'Implicit TLS':c.starttls_used?'STARTTLS':c.transport_mode.startsWith('UNKNOWN')?'Unverified':c.transport_mode.includes('CLEARTEXT')?'Cleartext':c.transport_mode}</td><td><span className={`assessment ${c.security_status.toLowerCase()}`}><i/>{c.security_status==='SECURE'?'Baseline passed':c.security_status==='CRITICAL'?'High risk':'Review needed'}</span></td><td><ArrowRight size={15}/></td></tr>)}</tbody></table>{!sessions.length&&<div className="empty-state">No sessions match these filters.</div>}</div></section>
    <div className="dashboard-footnote"><ShieldCheck size={15}/> Passive evidence only. Encrypted mail contents are not decrypted. AI outliers are analyst leads, not proof of compromise.</div>
  </div>;
};
