from app.models import (
    Investigation,
    SummaryStats,
    NetworkNode,
    NetworkConnection,
    ConnectionEvidence,
    PlainLanguageExploration,
    SecurityFinding,
)
from app.analysis.evidence import Evidence
from app.analysis.scoring import SecurityPosture

DEMO_INVESTIGATION = Investigation(
    id="INV-2026-001",
    filename="mail_gateway_capture.pcap",
    capture_date="2026-09-29 18:42:15 UTC",
    status="completed",
    is_simulated=True,
    data_source="SIMULATED",
    sha256_hash="e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    sha256_short="e3b0c44298fc",
    analysis_engine="SecureMailScope Deterministic Rule Engine v0.3 (SIMULATED PROTOTYPE)",
    summary=SummaryStats(
        sessions_analyzed=104,
        secure_sessions=81,
        warning_sessions=14,
        critical_sessions=9,
    ),
    security_posture=SecurityPosture(
        status="CRITICAL",
        findings_count=6,
        critical_count=2,
        high_count=2,
        medium_count=1,
        low_count=0,
        info_count=1,
        passed_checks=2,
        coverage_gaps=0,
    ),
    nodes=[
        NetworkNode(
            id="node-external-sender",
            label="External Sender (198.51.100.24)",
            role="Originating Mail User Agent / External Relay",
            ip_address="198.51.100.24",
            hostname="mail-outbound.external-partner.org",
            is_external=True,
            security_posture="secure",
        ),
        NetworkNode(
            id="node-partner2",
            label="Secondary Partner (198.51.100.25)",
            role="External Partner Relay",
            ip_address="198.51.100.25",
            hostname="relay-east.partner-network.net",
            is_external=True,
            security_posture="secure",
        ),
        NetworkNode(
            id="node-mail-gateway",
            label="Mail Gateway (203.0.113.10)",
            role="Edge Security Perimeter Gateway / Inbound MX",
            ip_address="203.0.113.10",
            hostname="mx1.security-perimeter.gov.in",
            is_external=False,
            security_posture="secure",
        ),
        NetworkNode(
            id="node-regional-gw",
            label="Regional Gateway (203.0.113.11)",
            role="Regional Ingress Gateway",
            ip_address="203.0.113.11",
            hostname="mx-regional.gov.in",
            is_external=False,
            security_posture="secure",
        ),
        NetworkNode(
            id="node-relay-server",
            label="Relay Server (10.240.12.5)",
            role="Internal Mail Transfer Agent (MTA) Hub",
            ip_address="10.240.12.5",
            hostname="mta-internal-relay.corp.lan",
            is_external=False,
            security_posture="warning",
        ),
        NetworkNode(
            id="node-dept-hub",
            label="Dept Mail Hub (10.240.12.6)",
            role="Departmental Sub-Relay",
            ip_address="10.240.12.6",
            hostname="dept-mta.corp.lan",
            is_external=False,
            security_posture="warning",
        ),
        NetworkNode(
            id="node-accounting",
            label="Accounting Agent (172.16.50.12)",
            role="Finance Dispatch Client",
            ip_address="172.16.50.12",
            hostname="finance-agent.internal.lan",
            is_external=False,
            security_posture="warning",
        ),
        NetworkNode(
            id="node-insecure-client",
            label="Legacy Workstation (10.10.1.4)",
            role="Legacy Automated Dispatch Client",
            ip_address="10.10.1.4",
            hostname="ws-dispatch.corp.lan",
            is_external=False,
            security_posture="critical",
        ),
        NetworkNode(
            id="node-research-gw",
            label="Research Lab (192.0.2.77)",
            role="Secure Experimental Node",
            ip_address="192.0.2.77",
            hostname="research-node.lab.org",
            is_external=True,
            security_posture="secure",
        ),
        NetworkNode(
            id="node-monitor-probe",
            label="Monitoring Probe (10.200.4.15)",
            role="Health Monitoring Probe",
            ip_address="10.200.4.15",
            hostname="mon-probe-01.mgmt.lan",
            is_external=False,
            security_posture="secure",
        ),
        NetworkNode(
            id="node-notify-service",
            label="Notification Svc (10.200.4.18)",
            role="Alert Notification Service",
            ip_address="10.200.4.18",
            hostname="alert-svc.corp.lan",
            is_external=False,
            security_posture="secure",
        ),
        NetworkNode(
            id="node-mailbox-sync",
            label="Sync Agent (10.240.14.90)",
            role="Mailbox Sync Daemon",
            ip_address="10.240.14.90",
            hostname="sync-agent.corp.lan",
            is_external=False,
            security_posture="warning",
        ),
        NetworkNode(
            id="node-destination-server",
            label="Destination Mail Server (10.240.12.88)",
            role="Final Mailbox Storage & Local Delivery Agent",
            ip_address="10.240.12.88",
            hostname="mailbox-storage.internal.lan",
            is_external=False,
            security_posture="critical",
        ),
    ],
    connections=[
        NetworkConnection(
            id="conn-ext-gw",
            source_node_id="node-external-sender",
            target_node_id="node-mail-gateway",
            source_label="External Sender (198.51.100.24)",
            target_label="Mail Gateway (203.0.113.10)",
            protocol="SMTP",
            transport_mode="Explicit TLS / STARTTLS",
            tls_version="TLS 1.3",
            cipher_suite="TLS_AES_256_GCM_SHA384",
            security_status="SECURE",
            session_id="SMTP-019",
            has_pfs=True,
            has_aead=True,
            starttls_advertised=True,
            starttls_used=True,
            explanation=PlainLanguageExploration(
                headline="Modern Transport Security Active",
                summary="External sender established a fully encrypted session using the modern TLS 1.3 standard with authenticated 256-bit encryption.",
                why_it_matters="Protects against passive wiretapping, man-in-the-middle tampering, and eavesdropping over untrusted public transit networks.",
                evidence_summary="Simulated Session SMTP-019: ClientHello matched TLS 1.3 supported_versions; Server negotiated TLS_AES_256_GCM_SHA384 with ephemeral ECDH key exchange.",
                recommended_action="Maintain current strict configuration. Enforce cipher suite whitelist across all perimeter endpoints.",
            ),
            evidence=ConnectionEvidence(
                session_id="SMTP-019",
                handshake_record="TLSv1.3 Handshake Record: ServerHello (Version: 0x0303, Supported_Version: 0x0304)",
                cipher_suite_hex="0x1302 (TLS_AES_256_GCM_SHA384)",
                protocol_version_hex="0x0304 (TLS 1.3)",
                ports="58412 → 25",
                packet_count=64,
            ),
        ),
        NetworkConnection(
            id="conn-partner2-gw",
            source_node_id="node-partner2",
            target_node_id="node-mail-gateway",
            source_label="Secondary Partner (198.51.100.25)",
            target_label="Mail Gateway (203.0.113.10)",
            protocol="SMTP",
            transport_mode="Explicit TLS / STARTTLS",
            tls_version="TLS 1.3",
            cipher_suite="TLS_AES_128_GCM_SHA256",
            security_status="SECURE",
            session_id="SMTP-022",
            has_pfs=True,
            has_aead=True,
            starttls_advertised=True,
            starttls_used=True,
            explanation=PlainLanguageExploration(
                headline="Modern TLS 1.3 Session",
                summary="Secondary partner established modern TLS 1.3 with AES-128-GCM and ephemeral key exchange.",
                why_it_matters="Ensures modern forward secrecy and transport integrity.",
                evidence_summary="Simulated Session SMTP-022: TLS 1.3 negotiated with AES-128-GCM.",
                recommended_action="Maintain configuration.",
            ),
            evidence=ConnectionEvidence(
                session_id="SMTP-022",
                handshake_record="TLSv1.3 Handshake Record: ServerHello",
                cipher_suite_hex="0x1301",
                protocol_version_hex="0x0304",
                ports="51204 → 25",
                packet_count=48,
            ),
        ),
        NetworkConnection(
            id="conn-gw-relay",
            source_node_id="node-mail-gateway",
            target_node_id="node-relay-server",
            source_label="Mail Gateway (203.0.113.10)",
            target_label="Relay Server (10.240.12.5)",
            protocol="SMTP",
            transport_mode="STARTTLS",
            tls_version="TLS 1.2",
            cipher_suite="TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
            security_status="SECURE",
            session_id="SMTP-028",
            has_pfs=True,
            has_aead=True,
            starttls_advertised=True,
            starttls_used=True,
            explanation=PlainLanguageExploration(
                headline="Standard Cryptographic Protection",
                summary="Perimeter gateway connected to the internal relay using standard TLS 1.2 with elliptic curve Diffie-Hellman key exchange.",
                why_it_matters="Ensures privacy and forward secrecy between perimeter inspection tier and internal relay queues.",
                evidence_summary="Simulated Session SMTP-028: STARTTLS command confirmed (220 2.0.0 Ready to start TLS); TLS 1.2 ECDHE exchange verified.",
                recommended_action="Plan upgrade to TLS 1.3 to remove legacy handshake roundtrips and enable 0-RTT protections.",
            ),
            evidence=ConnectionEvidence(
                session_id="SMTP-028",
                handshake_record="SMTP EHLO / STARTTLS → 220 2.0.0 Ready → ClientHello (TLS 1.2)",
                cipher_suite_hex="0xC02F (TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256)",
                protocol_version_hex="0x0303 (TLS 1.2)",
                ports="41908 → 587",
                packet_count=52,
            ),
        ),
        NetworkConnection(
            id="conn-regional-relay",
            source_node_id="node-regional-gw",
            target_node_id="node-relay-server",
            source_label="Regional Gateway (203.0.113.11)",
            target_label="Relay Server (10.240.12.5)",
            protocol="SMTP",
            transport_mode="STARTTLS",
            tls_version="TLS 1.2",
            cipher_suite="TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
            security_status="SECURE",
            session_id="SMTP-031",
            has_pfs=True,
            has_aead=True,
            starttls_advertised=True,
            starttls_used=True,
            explanation=PlainLanguageExploration(
                headline="Modern Transport Security Active",
                summary="Regional ingress gateway negotiated TLS 1.2 with 256-bit AES-GCM and ECDHE forward secrecy.",
                why_it_matters="Protects inter-gateway relay transit against wiretapping.",
                evidence_summary="Simulated Session SMTP-031: TLS 1.2 verified.",
                recommended_action="Maintain configuration.",
            ),
            evidence=ConnectionEvidence(
                session_id="SMTP-031",
                handshake_record="TLS 1.2 ServerHello (ECDHE-RSA-AES256-GCM)",
                cipher_suite_hex="0xC030",
                protocol_version_hex="0x0303",
                ports="39402 → 587",
                packet_count=44,
            ),
        ),
        NetworkConnection(
            id="conn-relay-dest",
            source_node_id="node-relay-server",
            target_node_id="node-destination-server",
            source_label="Relay Server (10.240.12.5)",
            target_label="Destination Mail Server (10.240.12.88)",
            protocol="SMTP",
            transport_mode="STARTTLS",
            tls_version="TLS 1.0",
            cipher_suite="TLS_RSA_WITH_3DES_EDE_CBC_SHA",
            security_status="CRITICAL",
            session_id="SMTP-042",
            has_pfs=False,
            has_aead=False,
            starttls_advertised=True,
            starttls_used=True,
            explanation=PlainLanguageExploration(
                headline="Old transport-security protocol detected (TLS 1.0 & Weak 3DES Cipher)",
                summary="The internal relay negotiated an obsolete cryptographic protocol (TLS 1.0) and a vulnerable cipher (3DES-CBC) when transferring mail to the destination mailbox server.",
                why_it_matters="An obsolete TLS version weakens the protection of communication between these mail servers. TLS 1.0 is deprecated (RFC 8996), lacks modern authenticated encryption (AEAD), has known cryptographic flaws (BEAST), and 3DES is vulnerable to Sweet32 collision attacks.",
                evidence_summary="Simulated Session SMTP-042: Server negotiated ProtocolVersion 0x0301 (TLS 1.0); selected cipher suite 0x000A (TLS_RSA_WITH_3DES_EDE_CBC_SHA).",
                recommended_action="1. Immediately disable TLS 1.0 and TLS 1.1 on mailbox-storage.internal.lan.\n2. Configure destination server to mandate TLS 1.2 or TLS 1.3 minimum.",
            ),
            evidence=ConnectionEvidence(
                session_id="SMTP-042",
                handshake_record="ServerHello: Version 0x0301 (TLS 1.0), Cipher: 0x000A (TLS_RSA_WITH_3DES_EDE_CBC_SHA)",
                cipher_suite_hex="0x000A (TLS_RSA_WITH_3DES_EDE_CBC_SHA)",
                protocol_version_hex="0x0301 (TLS 1.0 - DEPRECATED)",
                ports="38210 → 25",
                packet_count=38,
            ),
        ),
        NetworkConnection(
            id="conn-dept-dest",
            source_node_id="node-dept-hub",
            target_node_id="node-destination-server",
            source_label="Dept Mail Hub (10.240.12.6)",
            target_label="Destination Mail Server (10.240.12.88)",
            protocol="SMTP",
            transport_mode="STARTTLS",
            tls_version="TLS 1.0",
            cipher_suite="TLS_RSA_WITH_RC4_128_SHA",
            security_status="CRITICAL",
            session_id="SMTP-049",
            has_pfs=False,
            has_aead=False,
            starttls_advertised=True,
            starttls_used=True,
            explanation=PlainLanguageExploration(
                headline="Deprecated RC4 Cipher Suite Detected",
                summary="Department hub negotiated prohibited RC4 stream cipher over deprecated TLS 1.0.",
                why_it_matters="RC4 has severe cryptographic biases and is prohibited by RFC 7465.",
                evidence_summary="Simulated Session SMTP-049: TLS_RSA_WITH_RC4_128_SHA negotiated.",
                recommended_action="Disable RC4 cipher suites globally.",
            ),
            evidence=ConnectionEvidence(
                session_id="SMTP-049",
                handshake_record="ServerHello: Version 0x0301, Cipher 0x0005 (RC4)",
                cipher_suite_hex="0x0005",
                protocol_version_hex="0x0301",
                ports="40120 → 25",
                packet_count=32,
            ),
        ),
        NetworkConnection(
            id="conn-acct-relay",
            source_node_id="node-accounting",
            target_node_id="node-relay-server",
            source_label="Accounting Agent (172.16.50.12)",
            target_label="Relay Server (10.240.12.5)",
            protocol="SMTP",
            transport_mode="STARTTLS",
            tls_version="TLS 1.1",
            cipher_suite="TLS_RSA_WITH_AES_128_CBC_SHA",
            security_status="WARNING",
            session_id="SMTP-055",
            has_pfs=False,
            has_aead=False,
            starttls_advertised=True,
            starttls_used=True,
            explanation=PlainLanguageExploration(
                headline="Deprecated TLS 1.1 Protocol",
                summary="Finance agent negotiated deprecated TLS 1.1 with CBC cipher mode.",
                why_it_matters="TLS 1.1 is deprecated under RFC 8996.",
                evidence_summary="Simulated Session SMTP-055: TLS 1.1 observed.",
                recommended_action="Upgrade client to support TLS 1.2 or TLS 1.3.",
            ),
            evidence=ConnectionEvidence(
                session_id="SMTP-055",
                handshake_record="ServerHello: Version 0x0302 (TLS 1.1)",
                cipher_suite_hex="0x002F",
                protocol_version_hex="0x0302",
                ports="42188 → 587",
                packet_count=28,
            ),
        ),
        NetworkConnection(
            id="conn-insecure-relay",
            source_node_id="node-insecure-client",
            target_node_id="node-relay-server",
            source_label="Legacy Workstation (10.10.1.4)",
            target_label="Relay Server (10.240.12.5)",
            protocol="SMTP",
            transport_mode="CLEARTEXT (STARTTLS Offered but Not Used)",
            tls_version="None",
            cipher_suite="NONE (Unencrypted / Plaintext)",
            security_status="CRITICAL",
            session_id="SMTP-STREAM-088",
            has_pfs=False,
            has_aead=False,
            starttls_advertised=True,
            starttls_used=False,
            auth_observed=True,
            auth_before_tls=True,
            explanation=PlainLanguageExploration(
                headline="Authentication Transmitted Over Cleartext",
                summary="Client issued authentication commands over an unencrypted channel without establishing TLS, despite the server advertising STARTTLS.",
                why_it_matters="Transmitting credentials over unencrypted mail transport allows passive network eavesdroppers to harvest account passwords.",
                evidence_summary="Simulated Session SMTP-STREAM-088: AUTH LOGIN command observed before TLS.",
                recommended_action="Mandate STARTTLS before accepting AUTH commands on the mail server.",
            ),
            evidence=ConnectionEvidence(
                session_id="SMTP-STREAM-088",
                handshake_record="TCP Stream (CLEARTEXT - Auth Before TLS)",
                cipher_suite_hex=None,
                protocol_version_hex=None,
                ports="1470 → 25",
                packet_count=22,
            ),
        ),
        NetworkConnection(
            id="conn-research-gw",
            source_node_id="node-research-gw",
            target_node_id="node-mail-gateway",
            source_label="Research Lab (192.0.2.77)",
            target_label="Mail Gateway (203.0.113.10)",
            protocol="SMTP",
            transport_mode="Explicit TLS / STARTTLS",
            tls_version="TLS 1.3",
            cipher_suite="TLS_CHACHA20_POLY1305_SHA256",
            security_status="SECURE",
            session_id="SMTP-061",
            has_pfs=True,
            has_aead=True,
            starttls_advertised=True,
            starttls_used=True,
            explanation=PlainLanguageExploration(
                headline="Modern TLS 1.3 with ChaCha20-Poly1305",
                summary="Research gateway negotiated TLS 1.3 with ChaCha20-Poly1305 AEAD cipher.",
                why_it_matters="Provides modern forward secrecy and robust authenticated encryption.",
                evidence_summary="Simulated Session SMTP-061: TLS 1.3 ChaCha20-Poly1305 verified.",
                recommended_action="Maintain configuration.",
            ),
            evidence=ConnectionEvidence(
                session_id="SMTP-061",
                handshake_record="TLS 1.3 ServerHello (ChaCha20-Poly1305)",
                cipher_suite_hex="0x1303",
                protocol_version_hex="0x0304",
                ports="53902 → 25",
                packet_count=36,
            ),
        ),
        NetworkConnection(
            id="conn-mon-relay",
            source_node_id="node-monitor-probe",
            target_node_id="node-relay-server",
            source_label="Monitoring Probe (10.200.4.15)",
            target_label="Relay Server (10.240.12.5)",
            protocol="SMTP",
            transport_mode="STARTTLS",
            tls_version="TLS 1.2",
            cipher_suite="TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
            security_status="SECURE",
            session_id="SMTP-071",
            has_pfs=True,
            has_aead=True,
            starttls_advertised=True,
            starttls_used=True,
            explanation=PlainLanguageExploration(
                headline="Modern TLS 1.2 with ECDSA",
                summary="Monitoring probe authenticated using ECDSA certificate and ECDHE key exchange over TLS 1.2.",
                why_it_matters="Provides strong authentication and forward secrecy.",
                evidence_summary="Simulated Session SMTP-071: ECDHE-ECDSA-AES128-GCM active.",
                recommended_action="Maintain configuration.",
            ),
            evidence=ConnectionEvidence(
                session_id="SMTP-071",
                handshake_record="TLS 1.2 ServerHello (ECDHE-ECDSA)",
                cipher_suite_hex="0xC02B",
                protocol_version_hex="0x0303",
                ports="47102 → 587",
                packet_count=30,
            ),
        ),
        NetworkConnection(
            id="conn-notify-relay",
            source_node_id="node-notify-service",
            target_node_id="node-relay-server",
            source_label="Notification Svc (10.200.4.18)",
            target_label="Relay Server (10.240.12.5)",
            protocol="SMTP",
            transport_mode="STARTTLS",
            tls_version="TLS 1.2",
            cipher_suite="TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
            security_status="SECURE",
            session_id="SMTP-075",
            has_pfs=True,
            has_aead=True,
            starttls_advertised=True,
            starttls_used=True,
            explanation=PlainLanguageExploration(
                headline="Standard TLS 1.2 Ingestion",
                summary="Notification service delivers automated alerts over verified TLS 1.2 channel.",
                why_it_matters="Secures internal application-to-MTA alert pipelines.",
                evidence_summary="Simulated Session SMTP-075: TLS 1.2 verified.",
                recommended_action="Maintain configuration.",
            ),
            evidence=ConnectionEvidence(
                session_id="SMTP-075",
                handshake_record="TLS 1.2 ServerHello",
                cipher_suite_hex="0xC02F",
                protocol_version_hex="0x0303",
                ports="48910 → 587",
                packet_count=34,
            ),
        ),
        NetworkConnection(
            id="conn-sync-dest",
            source_node_id="node-mailbox-sync",
            target_node_id="node-destination-server",
            source_label="Sync Agent (10.240.14.90)",
            target_label="Destination Mail Server (10.240.12.88)",
            protocol="IMAP",
            transport_mode="Mixed (STARTTLS & CLEARTEXT)",
            tls_version="TLS 1.2",
            cipher_suite="TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
            security_status="WARNING",
            session_id="IMAP-082",
            has_pfs=True,
            has_aead=True,
            starttls_advertised=True,
            starttls_used=True,
            explanation=PlainLanguageExploration(
                headline="Mixed Transport Behavior on IMAP Channel",
                summary="Mailbox sync daemon connected via TLS 1.2 in session 1, but also initiated an unencrypted cleartext IMAP connection in session 2.",
                why_it_matters="Intermittent cleartext transport exposes mailbox synchronization metadata.",
                evidence_summary="Simulated Session IMAP-082: Inconsistent transport encryption observed across sessions.",
                recommended_action="Enforce mandatory Direct TLS on port 993 for all IMAP clients.",
            ),
            evidence=ConnectionEvidence(
                session_id="IMAP-082",
                handshake_record="IMAP STARTTLS / CLEARTEXT mixed",
                cipher_suite_hex="0xC02F",
                protocol_version_hex="0x0303",
                ports="55120 → 143",
                packet_count=26,
            ),
        ),
    ],
    findings=[
        SecurityFinding(
            id="FIND-001",
            title="Deprecated TLS Version (TLS 1.0 Detected)",
            severity="CRITICAL",
            category="Protocol Deprecation",
            status="FAIL",
            confidence="HIGH",
            affected_connection_id="conn-relay-dest",
            location="Relay Server → Destination Mail Server",
            plain_explanation="This simulated session negotiated TLS 1.0, an obsolete transport-security protocol officially deprecated by RFC 8996 and forbidden under modern cybersecurity baselines.",
            why_it_matters="An obsolete TLS version weakens the protection of communication between these mail servers, exposing traffic to cryptographic degradation and decryption vulnerabilities.",
            evidence="Simulated Session SMTP-042: ServerHello Handshake Record Version: 0x0301 / TLS 1.0",
            evidence_items=[
                Evidence(
                    type="OBSERVED",
                    field="tls_version",
                    value="TLS 1.0",
                    source="TLS Handshake ServerHello",
                    description="Negotiated deprecated TLS 1.0 protocol.",
                )
            ],
            recommendation="Disable TLS 1.0 and TLS 1.1 on both MTA relay and destination mailbox server. Enforce TLS 1.2 as the minimum acceptable version.",
            rule_id="SMS-TLSVER-001",
            references=["RFC 8996", "NIST SP 800-52 Rev. 2"],
        ),
        SecurityFinding(
            id="FIND-002",
            title="Weak 64-Bit Block Cipher Suite (Sweet32 Vulnerability)",
            severity="HIGH",
            category="Cryptographic Strength",
            status="FAIL",
            confidence="HIGH",
            affected_connection_id="conn-relay-dest",
            location="Relay Server → Destination Mail Server",
            plain_explanation="The connection negotiated 3DES with CBC mode (TLS_RSA_WITH_3DES_EDE_CBC_SHA), which relies on a legacy 64-bit block cipher without authenticated encryption (AEAD).",
            why_it_matters="64-bit block ciphers are susceptible to Sweet32 birthday collision attacks, enabling eavesdroppers to recover plain text during high-volume message delivery.",
            evidence="Simulated Session SMTP-042: Negotiated CipherSuite 0x000A (TLS_RSA_WITH_3DES_EDE_CBC_SHA)",
            evidence_items=[
                Evidence(
                    type="OBSERVED",
                    field="cipher_suite",
                    value="TLS_RSA_WITH_3DES_EDE_CBC_SHA",
                    source="TLS Handshake ServerHello",
                    description="Negotiated 64-bit block cipher 3DES.",
                )
            ],
            recommendation="Remove all 3DES, RC4, and CBC-mode ciphers from the server cipher suite list. Enforce AEAD ciphers (AES-GCM or CHACHA20-POLY1305).",
            rule_id="SMS-CIPHER-001",
            references=["RFC 7465", "RFC 7540", "NIST SP 800-52 Rev. 2"],
        ),
        SecurityFinding(
            id="FIND-003",
            title="Static Key Exchange Without Forward Secrecy",
            severity="MEDIUM",
            category="Key Exchange",
            status="WARN",
            confidence="HIGH",
            affected_connection_id="conn-relay-dest",
            location="Relay Server → Destination Mail Server",
            plain_explanation="The connection negotiated static RSA key exchange without ephemeral Diffie-Hellman parameters (no PFS).",
            why_it_matters="Compromise of the server private key at any point in the future allows retroactive decryption of past session captures.",
            evidence="Simulated Session SMTP-042: RSA static key exchange cipher suite active",
            evidence_items=[
                Evidence(
                    type="OBSERVED",
                    field="has_pfs",
                    value=False,
                    source="TLS Handshake Cipher Suite",
                    description="Static RSA key exchange lacking Forward Secrecy.",
                )
            ],
            recommendation="Configure mail server to disable static RSA key exchange suites and prioritize ECDHE.",
            rule_id="SMS-PFS-001",
            references=["RFC 8446", "NIST SP 800-52 Rev. 2"],
        ),
        SecurityFinding(
            id="FIND-004",
            title="Modern TLS 1.3 Transport Active",
            severity="INFO",
            category="Cryptographic Baseline",
            status="PASS",
            confidence="HIGH",
            affected_connection_id="conn-ext-gw",
            location="External Sender → Mail Gateway",
            plain_explanation="Edge perimeter successfully negotiated TLS 1.3 with AES-256-GCM and ephemeral Diffie-Hellman key exchange.",
            why_it_matters="Provides maximum cryptographic hygiene, forward secrecy, and zero plain-text metadata leakage during handshake.",
            evidence="Simulated Session SMTP-019: TLS 1.3 supported_versions extension matched, TLS_AES_256_GCM_SHA384",
            evidence_items=[
                Evidence(
                    type="OBSERVED",
                    field="tls_version",
                    value="TLS 1.3",
                    source="TLS Handshake ServerHello",
                    description="Negotiated TLS 1.3 with AES-256-GCM.",
                )
            ],
            recommendation="Maintain current security profile as standard baseline across all ingress mail relays.",
            rule_id="SMS-TLSVER-002",
            references=["RFC 8446", "NIST SP 800-52 Rev. 2"],
        ),
        SecurityFinding(
            id="FIND-005",
            title="Authentication Before TLS Protection",
            severity="CRITICAL",
            category="Credential Protection",
            status="FAIL",
            confidence="HIGH",
            affected_connection_id="conn-insecure-relay",
            location="Legacy Workstation → Relay Server",
            plain_explanation="Authentication commands and account credentials were submitted over an unencrypted cleartext session before establishing TLS encryption.",
            why_it_matters="Transmitting credentials over cleartext allows eavesdroppers on the network path to harvest passwords and gain unauthorized access.",
            evidence="Simulated Session SMTP-STREAM-088: AUTH LOGIN observed over cleartext TCP port 25.",
            evidence_items=[
                Evidence(
                    type="OBSERVED",
                    field="auth_before_tls",
                    value=True,
                    source="SMTP Command Stream",
                    description="Cleartext authentication observed before TLS handshake.",
                )
            ],
            recommendation="Configure mail server to mandate STARTTLS before advertising or accepting AUTH commands.",
            rule_id="SMS-AUTH-001",
            references=["RFC 8314", "RFC 4954"],
        ),
        SecurityFinding(
            id="FIND-006",
            title="Cleartext Email Transport",
            severity="HIGH",
            category="Transport Encryption",
            status="FAIL",
            confidence="HIGH",
            affected_connection_id="conn-insecure-relay",
            location="Legacy Workstation → Relay Server",
            plain_explanation="Email transit proceeded unencrypted without TLS protection despite server advertising STARTTLS capability.",
            why_it_matters="Application payloads and email transit metadata are exposed to passive wiretapping.",
            evidence="Simulated Session SMTP-STREAM-088: STARTTLS advertised but unused.",
            evidence_items=[
                Evidence(
                    type="OBSERVED",
                    field="transport_mode",
                    value="CLEARTEXT",
                    source="Transport Stream",
                    description="Session operated in cleartext without TLS.",
                )
            ],
            recommendation="Enforce mandatory TLS encryption for all client submissions.",
            rule_id="SMS-TLS-001",
            references=["RFC 8314", "RFC 3207"],
        ),
    ],
    observed_clients=[
        {
            "client_id": "SMTP:198.51.100.24",
            "protocol": "SMTP",
            "observed_ip": "198.51.100.24",
            "observed_tls_versions": ["TLS 1.3"],
            "supported_tls_versions": ["TLS 1.3", "TLS 1.2"],
            "observed_cipher_suites": ["TLS_AES_256_GCM_SHA384"],
            "offered_cipher_suites": ["TLS_AES_256_GCM_SHA384", "TLS_AES_128_GCM_SHA256", "TLS_CHACHA20_POLY1305_SHA256"],
            "starttls_observed": True,
            "starttls_used": True,
            "plaintext_observed": False,
            "forward_secrecy_observed": True,
            "evidence_quality": "STRONG",
            "evidence": [
                {
                    "type": "OBSERVED",
                    "field": "supported_tls_versions",
                    "value": ["TLS 1.3", "TLS 1.2"],
                    "source": "TLS ClientHello supported_versions",
                    "description": "Client explicitly offered modern TLS 1.3 and TLS 1.2.",
                }
            ],
            "session_count": 19,
        },
        {
            "client_id": "SMTP:198.51.100.25",
            "protocol": "SMTP",
            "observed_ip": "198.51.100.25",
            "observed_tls_versions": ["TLS 1.3"],
            "supported_tls_versions": ["TLS 1.3", "TLS 1.2"],
            "observed_cipher_suites": ["TLS_AES_128_GCM_SHA256"],
            "offered_cipher_suites": ["TLS_AES_128_GCM_SHA256", "TLS_AES_256_GCM_SHA384"],
            "starttls_observed": True,
            "starttls_used": True,
            "plaintext_observed": False,
            "forward_secrecy_observed": True,
            "evidence_quality": "STRONG",
            "evidence": [],
            "session_count": 14,
        },
        {
            "client_id": "SMTP:203.0.113.10",
            "protocol": "SMTP",
            "observed_ip": "203.0.113.10",
            "observed_tls_versions": ["TLS 1.2"],
            "supported_tls_versions": ["TLS 1.2"],
            "observed_cipher_suites": ["TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"],
            "offered_cipher_suites": ["TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256", "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"],
            "starttls_observed": True,
            "starttls_used": True,
            "plaintext_observed": False,
            "forward_secrecy_observed": True,
            "evidence_quality": "STRONG",
            "evidence": [],
            "session_count": 15,
        },
        {
            "client_id": "SMTP:203.0.113.11",
            "protocol": "SMTP",
            "observed_ip": "203.0.113.11",
            "observed_tls_versions": ["TLS 1.2"],
            "supported_tls_versions": ["TLS 1.2"],
            "observed_cipher_suites": ["TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"],
            "offered_cipher_suites": ["TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"],
            "starttls_observed": True,
            "starttls_used": True,
            "plaintext_observed": False,
            "forward_secrecy_observed": True,
            "evidence_quality": "STRONG",
            "evidence": [],
            "session_count": 12,
        },
        {
            "client_id": "SMTP:10.240.12.5",
            "protocol": "SMTP",
            "observed_ip": "10.240.12.5",
            "observed_tls_versions": ["TLS 1.0"],
            "supported_tls_versions": ["TLS 1.0"],
            "observed_cipher_suites": ["TLS_RSA_WITH_3DES_EDE_CBC_SHA"],
            "offered_cipher_suites": ["TLS_RSA_WITH_3DES_EDE_CBC_SHA", "TLS_RSA_WITH_RC4_128_SHA"],
            "starttls_observed": True,
            "starttls_used": True,
            "plaintext_observed": False,
            "forward_secrecy_observed": False,
            "evidence_quality": "STRONG",
            "evidence": [],
            "session_count": 8,
        },
        {
            "client_id": "SMTP:10.240.12.6",
            "protocol": "SMTP",
            "observed_ip": "10.240.12.6",
            "observed_tls_versions": ["TLS 1.0"],
            "supported_tls_versions": ["TLS 1.0"],
            "observed_cipher_suites": ["TLS_RSA_WITH_RC4_128_SHA"],
            "offered_cipher_suites": ["TLS_RSA_WITH_RC4_128_SHA"],
            "starttls_observed": True,
            "starttls_used": True,
            "plaintext_observed": False,
            "forward_secrecy_observed": False,
            "evidence_quality": "STRONG",
            "evidence": [],
            "session_count": 6,
        },
        {
            "client_id": "SMTP:172.16.50.12",
            "protocol": "SMTP",
            "observed_ip": "172.16.50.12",
            "observed_tls_versions": ["TLS 1.1"],
            "supported_tls_versions": [],
            "observed_cipher_suites": ["TLS_RSA_WITH_AES_128_CBC_SHA"],
            "offered_cipher_suites": [],
            "starttls_observed": True,
            "starttls_used": True,
            "plaintext_observed": False,
            "forward_secrecy_observed": False,
            "evidence_quality": "PARTIAL",
            "evidence": [],
            "session_count": 5,
        },
        {
            "client_id": "SMTP:10.10.1.4",
            "protocol": "SMTP",
            "observed_ip": "10.10.1.4",
            "observed_tls_versions": [],
            "supported_tls_versions": [],
            "observed_cipher_suites": [],
            "offered_cipher_suites": [],
            "starttls_observed": True,
            "starttls_used": False,
            "plaintext_observed": True,
            "forward_secrecy_observed": False,
            "evidence_quality": "STRONG",
            "evidence": [],
            "session_count": 4,
        },
        {
            "client_id": "SMTP:192.0.2.77",
            "protocol": "SMTP",
            "observed_ip": "192.0.2.77",
            "observed_tls_versions": ["TLS 1.3"],
            "supported_tls_versions": ["TLS 1.3"],
            "observed_cipher_suites": ["TLS_CHACHA20_POLY1305_SHA256"],
            "offered_cipher_suites": ["TLS_CHACHA20_POLY1305_SHA256", "TLS_AES_256_GCM_SHA384"],
            "starttls_observed": True,
            "starttls_used": True,
            "plaintext_observed": False,
            "forward_secrecy_observed": True,
            "evidence_quality": "STRONG",
            "evidence": [],
            "session_count": 3,
        },
        {
            "client_id": "SMTP:10.200.4.15",
            "protocol": "SMTP",
            "observed_ip": "10.200.4.15",
            "observed_tls_versions": ["TLS 1.2"],
            "supported_tls_versions": ["TLS 1.2"],
            "observed_cipher_suites": ["TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256"],
            "offered_cipher_suites": ["TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256"],
            "starttls_observed": True,
            "starttls_used": True,
            "plaintext_observed": False,
            "forward_secrecy_observed": True,
            "evidence_quality": "STRONG",
            "evidence": [],
            "session_count": 7,
        },
        {
            "client_id": "SMTP:10.200.4.18",
            "protocol": "SMTP",
            "observed_ip": "10.200.4.18",
            "observed_tls_versions": ["TLS 1.2"],
            "supported_tls_versions": ["TLS 1.2"],
            "observed_cipher_suites": ["TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"],
            "offered_cipher_suites": ["TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"],
            "starttls_observed": True,
            "starttls_used": True,
            "plaintext_observed": False,
            "forward_secrecy_observed": True,
            "evidence_quality": "STRONG",
            "evidence": [],
            "session_count": 9,
        },
        {
            "client_id": "IMAP:10.240.14.90",
            "protocol": "IMAP",
            "observed_ip": "10.240.14.90",
            "observed_tls_versions": ["TLS 1.2"],
            "supported_tls_versions": ["TLS 1.2"],
            "observed_cipher_suites": ["TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"],
            "offered_cipher_suites": ["TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"],
            "starttls_observed": True,
            "starttls_used": True,
            "plaintext_observed": True,
            "forward_secrecy_observed": True,
            "evidence_quality": "PARTIAL",
            "evidence": [],
            "session_count": 2,
        },
    ],
    replays=[
        {
            "session_id": "SMTP-STREAM-088",
            "protocol": "SMTP",
            "summary": {
                "session_id": "SMTP-STREAM-088",
                "protocol": "SMTP",
                "client_endpoint": "10.10.1.4:1470",
                "server_endpoint": "10.240.12.5:25",
                "started_at": "00.000s",
                "duration_ms": 1120.0,
                "initial_transport": "CLEARTEXT",
                "final_transport": "CLEARTEXT",
                "event_count": 8,
                "highest_security_state": "CRITICAL",
                "critical_event_id": "evt-088-5",
                "critical_event_title": "Authentication Before TLS",
                "related_findings": ["FIND-005", "FIND-006"],
            },
            "critical_moment": {
                "event_id": "evt-088-5",
                "title": "Authentication Before TLS",
                "reason": "Authentication occurred while the session remained unencrypted.",
                "rule_id": "SMS-AUTH-001",
                "severity": "CRITICAL",
            },
            "events": [
                {
                    "event_id": "evt-088-1",
                    "session_id": "SMTP-STREAM-088",
                    "relative_time_ms": 0.0,
                    "direction": "CLIENT_TO_SERVER",
                    "event_type": "TCP_CONNECTION_ESTABLISHED",
                    "title": "TCP Connection Established",
                    "description": "Client initiated TCP 3-way handshake to 10.240.12.5:25.",
                    "transport_state": "CONNECTED_CLEAR",
                    "security_state": "NEUTRAL",
                    "evidence_source": "Frame 1 (SYN)",
                    "metadata": {"client": "10.10.1.4:1470", "server": "10.240.12.5:25"},
                },
                {
                    "event_id": "evt-088-2",
                    "session_id": "SMTP-STREAM-088",
                    "relative_time_ms": 45.0,
                    "direction": "SERVER_TO_CLIENT",
                    "event_type": "SERVER_GREETING",
                    "title": "Server Greeting",
                    "description": "Mail server announced ready (SMTP 220 Service ready).",
                    "transport_state": "CONNECTED_CLEAR",
                    "security_state": "NEUTRAL",
                    "evidence_source": "Frame 3 (SMTP 220)",
                    "metadata": {"code": "220"},
                },
                {
                    "event_id": "evt-088-3",
                    "session_id": "SMTP-STREAM-088",
                    "relative_time_ms": 90.0,
                    "direction": "CLIENT_TO_SERVER",
                    "event_type": "CLIENT_GREETING",
                    "title": "Client Greeting (EHLO)",
                    "description": "Client greeted server via EHLO ws-dispatch.corp.lan.",
                    "transport_state": "CONNECTED_CLEAR",
                    "security_state": "NEUTRAL",
                    "evidence_source": "Frame 4 (EHLO)",
                    "metadata": {"command": "EHLO"},
                },
                {
                    "event_id": "evt-088-4",
                    "session_id": "SMTP-STREAM-088",
                    "relative_time_ms": 135.0,
                    "direction": "SERVER_TO_CLIENT",
                    "event_type": "STARTTLS_ADVERTISED",
                    "title": "STARTTLS Advertised",
                    "description": "Server advertised STARTTLS encryption capability.",
                    "transport_state": "TLS_AVAILABLE",
                    "security_state": "WARNING",
                    "evidence_source": "Frame 5 (250-STARTTLS)",
                    "related_rule_ids": ["SMS-STARTTLS-001"],
                    "metadata": {"capability": "STARTTLS"},
                },
                {
                    "event_id": "evt-088-5",
                    "session_id": "SMTP-STREAM-088",
                    "relative_time_ms": 210.0,
                    "direction": "CLIENT_TO_SERVER",
                    "event_type": "AUTHENTICATION_ATTEMPT",
                    "title": "Authentication Before TLS",
                    "description": "Client issued AUTH LOGIN command over unencrypted connection.",
                    "transport_state": "AUTHENTICATING_UNENCRYPTED",
                    "security_state": "CRITICAL",
                    "evidence_source": "Frame 7 (AUTH LOGIN)",
                    "related_rule_ids": ["SMS-AUTH-001"],
                    "metadata": {"command": "AUTH LOGIN"},
                },
                {
                    "event_id": "evt-088-6",
                    "session_id": "SMTP-STREAM-088",
                    "relative_time_ms": 320.0,
                    "direction": "SERVER_TO_CLIENT",
                    "event_type": "AUTHENTICATION_CHALLENGE",
                    "title": "Authentication Challenge",
                    "description": "Server responded with authentication challenge in cleartext.",
                    "transport_state": "AUTHENTICATING_UNENCRYPTED",
                    "security_state": "CRITICAL",
                    "evidence_source": "Frame 8 (334 Challenge)",
                    "metadata": {"code": "334"},
                },
                {
                    "event_id": "evt-088-7",
                    "session_id": "SMTP-STREAM-088",
                    "relative_time_ms": 780.0,
                    "direction": "CLIENT_TO_SERVER",
                    "event_type": "MAIL_TRANSACTION_STARTED",
                    "title": "Mail Transaction Initiated",
                    "description": "Client initiated mail transaction over cleartext session.",
                    "transport_state": "UNENCRYPTED_MAIL_DATA",
                    "security_state": "HIGH",
                    "evidence_source": "Frame 14 (MAIL FROM)",
                    "related_rule_ids": ["SMS-TLS-001"],
                    "metadata": {"command": "MAIL FROM"},
                },
                {
                    "event_id": "evt-088-8",
                    "session_id": "SMTP-STREAM-088",
                    "relative_time_ms": 1120.0,
                    "direction": "CLIENT_TO_SERVER",
                    "event_type": "SESSION_TERMINATED",
                    "title": "Session Terminated (QUIT)",
                    "description": "Client requested connection closure via QUIT.",
                    "transport_state": "SESSION_ENDED",
                    "security_state": "NEUTRAL",
                    "evidence_source": "Frame 22 (QUIT)",
                    "metadata": {"command": "QUIT"},
                },
            ],
        },
        {
            "session_id": "SMTP-STREAM-019",
            "protocol": "SMTP",
            "summary": {
                "session_id": "SMTP-STREAM-019",
                "protocol": "SMTP",
                "client_endpoint": "198.51.100.24:49210",
                "server_endpoint": "203.0.113.10:25",
                "started_at": "00.000s",
                "duration_ms": 850.0,
                "initial_transport": "CLEARTEXT",
                "final_transport": "TLS_PROTECTED",
                "event_count": 8,
                "highest_security_state": "SECURE",
                "critical_event_id": None,
                "critical_event_title": None,
                "related_findings": ["FIND-004"],
            },
            "critical_moment": None,
            "events": [
                {
                    "event_id": "evt-019-1",
                    "session_id": "SMTP-STREAM-019",
                    "relative_time_ms": 0.0,
                    "direction": "CLIENT_TO_SERVER",
                    "event_type": "TCP_CONNECTION_ESTABLISHED",
                    "title": "TCP Connection Established",
                    "description": "Client initiated TCP 3-way handshake to 203.0.113.10:25.",
                    "transport_state": "CONNECTED_CLEAR",
                    "security_state": "NEUTRAL",
                    "evidence_source": "Frame 1 (SYN)",
                    "metadata": {"client": "198.51.100.24:49210", "server": "203.0.113.10:25"},
                },
                {
                    "event_id": "evt-019-2",
                    "session_id": "SMTP-STREAM-019",
                    "relative_time_ms": 32.0,
                    "direction": "SERVER_TO_CLIENT",
                    "event_type": "SERVER_GREETING",
                    "title": "Server Greeting",
                    "description": "Mail server signaled service ready (SMTP 220).",
                    "transport_state": "CONNECTED_CLEAR",
                    "security_state": "NEUTRAL",
                    "evidence_source": "Frame 3 (SMTP 220 Ready)",
                    "metadata": {"code": "220"},
                },
                {
                    "event_id": "evt-019-3",
                    "session_id": "SMTP-STREAM-019",
                    "relative_time_ms": 65.0,
                    "direction": "CLIENT_TO_SERVER",
                    "event_type": "CLIENT_GREETING",
                    "title": "Client Greeting (EHLO)",
                    "description": "Client initiated communication via EHLO.",
                    "transport_state": "CONNECTED_CLEAR",
                    "security_state": "NEUTRAL",
                    "evidence_source": "Frame 4 (EHLO)",
                    "metadata": {"command": "EHLO"},
                },
                {
                    "event_id": "evt-019-4",
                    "session_id": "SMTP-STREAM-019",
                    "relative_time_ms": 98.0,
                    "direction": "SERVER_TO_CLIENT",
                    "event_type": "STARTTLS_ADVERTISED",
                    "title": "STARTTLS Capability Advertised",
                    "description": "Server offered STARTTLS transport encryption in capability list.",
                    "transport_state": "TLS_AVAILABLE",
                    "security_state": "SECURE",
                    "evidence_source": "Frame 5 (250-STARTTLS)",
                    "metadata": {"capability": "STARTTLS"},
                },
                {
                    "event_id": "evt-019-5",
                    "session_id": "SMTP-STREAM-019",
                    "relative_time_ms": 130.0,
                    "direction": "CLIENT_TO_SERVER",
                    "event_type": "STARTTLS_REQUESTED",
                    "title": "STARTTLS Requested",
                    "description": "Client issued STARTTLS command to upgrade to encrypted channel.",
                    "transport_state": "TLS_REQUESTED",
                    "security_state": "SECURE",
                    "evidence_source": "Frame 6 (STARTTLS)",
                    "metadata": {"command": "STARTTLS"},
                },
                {
                    "event_id": "evt-019-6",
                    "session_id": "SMTP-STREAM-019",
                    "relative_time_ms": 180.0,
                    "direction": "CLIENT_TO_SERVER",
                    "event_type": "TLS_HANDSHAKE_STARTED",
                    "title": "TLS Handshake Initiated (ClientHello)",
                    "description": "Client offered TLS 1.3 and modern AEAD cipher suites.",
                    "transport_state": "TLS_HANDSHAKE",
                    "security_state": "NEUTRAL",
                    "evidence_source": "Frame 8 (TLS ClientHello)",
                    "metadata": {"handshake": "ClientHello"},
                },
                {
                    "event_id": "evt-019-7",
                    "session_id": "SMTP-STREAM-019",
                    "relative_time_ms": 220.0,
                    "direction": "SERVER_TO_CLIENT",
                    "event_type": "TLS_ESTABLISHED",
                    "title": "TLS Established (TLS 1.3)",
                    "description": "Session upgraded to TLS 1.3 with TLS_AES_256_GCM_SHA384 and PFS.",
                    "transport_state": "TLS_PROTECTED",
                    "security_state": "SECURE",
                    "evidence_source": "Frame 10 (ServerHello / TLS 1.3)",
                    "related_rule_ids": ["SMS-TLSVER-002"],
                    "metadata": {"tls_version": "TLS 1.3", "cipher_suite": "TLS_AES_256_GCM_SHA384"},
                },
                {
                    "event_id": "evt-019-8",
                    "session_id": "SMTP-STREAM-019",
                    "relative_time_ms": 310.0,
                    "direction": "CLIENT_TO_SERVER",
                    "event_type": "AUTHENTICATION_ATTEMPT",
                    "title": "Authentication Attempt (Protected)",
                    "description": "Client submitted credentials inside verified TLS 1.3 encrypted tunnel.",
                    "transport_state": "TLS_PROTECTED",
                    "security_state": "SECURE",
                    "evidence_source": "Frame 12 (Protected AUTH)",
                    "metadata": {"command": "AUTH", "mode": "TLS_PROTECTED"},
                },
            ],
        },
    ],
)

# Automatically generate discovery and AI anomaly assessment for DEMO_INVESTIGATION
from app.discovery.engine import ClientDiscoveryEngine
DEMO_INVESTIGATION.discovery = ClientDiscoveryEngine().discover(DEMO_INVESTIGATION)
